const API_BASE_URL_DEVELOPMENT = 'http://localhost:5000/api';

const ENDPOINTS = {
    LOGIN_POST: 'Auth/login',
    REGISTER_POST: 'Auth/register',
    BOOK_GETALL: 'Book/getall',
    BOOK_SEARCH: 'Book/searchbook?term=',
    BOOK_DELETE: 'Book/delete',
    BOOK_UPDATE: 'Book/update',
    BOOK_ADD_LIST: 'Book/addbooklist',
    BOOK_GET: 'Book/get',
    BOOK_IMAGE_UPDATE: 'Book/setbookimage'
}

const constans = {
    API_URL_LOGIN_POST: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.LOGIN_POST}`,
    API_URL_REGISTER_POST: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.REGISTER_POST}`,
    API_URL_BOOK_GETALL: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.BOOK_GETALL}`,
    API_URL_BOOK_SEARCH: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.BOOK_SEARCH}`,
    API_URL_BOOK_DELETE: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.BOOK_DELETE}`,
    API_URL_BOOK_UPDATE: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.BOOK_UPDATE}`,
    API_URL_BOOK_ADD_LIST: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.BOOK_ADD_LIST}`,
    API_URL_BOOK_GET: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.BOOK_GET}`,
    API_URL_BOOK_IMAGE_UPDATE: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.BOOK_IMAGE_UPDATE}`,
}

export default constans;